src/environment.ts
src/reverse-proxy-handler.ts
src/secure-proxy-handler.ts

let to const nits

---

src/browser-realm.ts

Remove iframe from the document to `null` out `window.top`. This has a side effect of ignoring `debugger` statements in Chrome (while it continues to work in Firefox and Safari). See the code comment for the bug I filed against the Chrome devtools for this.

remove iframe from document to null out window.top.

---

src/shared.ts

It's as the PR title suggests ;)

Uncomment SharedArrayBuffer and Atomics because they exist in Chrome

---

src/environment.ts
src/shared.ts

Add `unconstruct()` helper to avoid global lookup of builtin constructors

Add unconstruct() helper

---

examples/custom-elements.js
examples/custom-events.js
examples/expandos.js
examples/getter-distortion.js
examples/web-components/index.html

This PR makes sure the expected output is logged correctly for demos.

fix example expected output

---

src/environment.ts

A minor tweak for debug consistency.

add key to console.error() log for prototype remapping

---

README.md

Does this seem correct? I was confused by this wording

doc - readme typo fix

---

examples/getter-distortion.js
examples/invalid-fetch.js
src/__tests__/freezing.spec.ts
src/__tests__/index.spec.ts
src/browser-realm.ts
src/environment.ts
src/node-realm.ts

* distortions as a map to be predictable when it comes to performance.

fixes #35: distortion map instead of a callback function

---

src/environment.ts
src/raw-value.ts
src/secure-value.ts

Related issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1042435#c4

Workaround for issue 1042435 in blick/chromium by wrapping apply and construct calls to DOM APIs

---

karma.config.js
package.json
test/distortions/getter.spec.js
test/distortions/methods.spec.js
test/dom/custom-element.spec.js
test/errors/boundary.spec.js
test/membrane/expandos.spec.js
test/membrane/globals.spec.js
test/membrane/object-graph-mutations.spec.js
yarn.lock

Adding basic integration tests via karma.

add karma configuration to run integration tests

---

src/raw-value.ts
src/secure-value.ts
src/shared.ts
test/membrane/internal-slot-protection.spec.js

This is just an internal refactor, with no implications on the users of this library.

improving get/set traps in both sides of the membrane

---

examples/errors.js
examples/invalid-fetch.js
src/__tests__/error.spec.ts
src/__tests__/freezing.spec.ts
src/__tests__/index.spec.ts
src/__tests__/reflection.spec.ts
src/browser-realm.ts
src/environment.ts
src/node-realm.ts
test/distortions/getter.spec.js
test/distortions/methods.spec.js
test/dom/custom-element.spec.js
test/errors/boundary.spec.js
test/membrane/document-all.spec.js
test/membrane/expandos.spec.js
test/membrane/globals.spec.js
test/membrane/internal-slot-protection.spec.js
test/membrane/object-graph-mutations.spec.js
test/membrane/symbols.spec.js

This PR is just an internal refactor, does not affect or change any functionality.

caching references of unforgeable and their descriptors per window reference in preparation for multi-window support

---

karma.config.js
package.json
yarn.lock

Run Karma tests with headless Chrome and Firefox

---

test/membrane/ownKeys.spec.js
test/membrane/super.spec.js

chore(membrane): Test for super.value writes

---

src/intrinsics.ts

* remapping of intrinsics that can produce objects with identity
* add AggregateError to intrinsics and reflective intrinsics as well (fixes issue #117)
* add extensive explanation of what and why to remap

improving intrinsics remapping

---

.circleci/config.yml
package.json

Integrate CircleCI (first pass, basic things)

Integrate CircleCI

---

src/blue.ts
src/browser-realm.ts
src/environment.ts
src/intrinsics.ts
src/node-realm.ts
src/red.ts
src/shared.ts
src/types.ts
src/window.ts

Reduce use of lower level helpers

@W-8868676@ feat(core) Reduce use of lower level helpers

---

.circleci/config.yml
.gitignore
karma.config.js
package.json
yarn.lock

- add coverage reporting to both test commands
- add merge & report commands
- add artifact storage to ci

chore: coverage reporting

---

packages/near-membrane-node/src/__tests__/index.spec.ts

Branch coverage: 
50% -> 100%, 2/4 -> 4/4

chore: exercise default options handling of createVirtualEnvironment

---

packages/near-membrane-base/src/__tests__/environment.spec.ts
packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/tsconfig.json
packages/near-membrane-base/tsconfig.types.json
packages/near-membrane-node/src/__tests__/index.spec.ts

test: @W-9323615@ near-membrane-base/src/environment.ts to 100% coverage

---

.circleci/config.yml
packages/near-membrane-base/src/__tests__/intrinsics.spec.ts

test: @W-9323615@ near-membrane-base/src/intrinsics.ts to 100% coverage

---

packages/near-membrane-base/src/blue.ts
packages/near-membrane-node/src/__tests__/index.spec.ts

chore: document unreachable or untested paths in near-membrane-base/src/blue

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-node/src/node-realm.ts

On hold until we discuss with @ravijayaramappa.

fix: add virtual environment SupportFlags

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/window.ts
packages/near-membrane-node/src/node-realm.ts

Cleanup pass on naming, types, arguments, etc.

chore: cleanup naming, types, arguments

---

.commitlintrc.js
babel.config.js
jest.config.js
karma.config.js
package.json
packages/near-membrane-base/.eslintrc.cjs
packages/near-membrane-base/.rolluprc.cjs
packages/near-membrane-base/package.json
packages/near-membrane-base/rollup.config.js
packages/near-membrane-dom/.eslintrc.cjs
packages/near-membrane-dom/.rolluprc.cjs
packages/near-membrane-dom/package.json
packages/near-membrane-node/.babelrc.cjs
packages/near-membrane-node/.eslintrc.cjs
packages/near-membrane-node/.rolluprc.cjs
packages/near-membrane-node/package.json
scripts/.eslintrc.cjs
scripts/babel/configs/node.cjs
scripts/package.json
scripts/rollup/configs/base.cjs
scripts/rollup/plugins/babel-output.cjs
yarn.lock

transpile syntax to baseline support

fix: transpile syntax to baseline support @W-10081191@

---

.eslintignore
.gitignore
.prettierignore
README.md
babel.config.js
package.json
packages/near-membrane-base/package.json
packages/near-membrane-dom/package.json
packages/near-membrane-node/package.json
scripts/babel/configs/base.cjs
scripts/babel/configs/node.cjs
scripts/rollup/configs/base.cjs
scripts/rollup/plugins/babel-output.cjs
test/environment/createvirtualenvironment-implementation.spec.js
yarn.lock

feat: narrow babel transforms for environment compatibility

feat: narrow babel transforms for environment compatibility

---

package.json
packages/near-membrane-base/package.json
packages/near-membrane-base/src/connector.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/package.json
packages/near-membrane-node/package.json
scripts/rollup/configs/base.cjs
yarn.lock

This PR aligns our build output with Locker and implements the same DEV_MODE logic so that we flip our mode when minified by LWC/LWR/Aura.

feat: detect minification by third parties

---

packages/near-membrane-base/src/connector.ts
packages/near-membrane-base/src/membrane.ts

feat: make a distinction between user debug_mode and locker local dev_mode

feat: make a distinction between user debug_mode and locker local dev_mode

---

packages/near-membrane-base/src/connector.ts
packages/near-membrane-base/src/membrane.ts

fix: use comments to indicate DEBUG_MODE

fix: use comments to indicate DEBUG_MODE

---

packages/near-membrane-dom/src/browser-realm.ts

feat: reduce abstraction of ObjectLookupOwnGetter

feat: reduce abstraction of ObjectLookupOwnGetter

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/intrinsics.ts
scripts/rollup/plugins/babel-output.cjs

chore: consistent length destructuring

chore: consistent length destructuring

---

packages/near-membrane-base/src/__tests__/environment.spec.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-node/src/__tests__/freezing.spec.js
test/environment/createvirtualenvironment-implementation.spec.js
test/membrane/array.spec.js
test/membrane/expandos.spec.js
test/membrane/freezing.spec.js
test/membrane/internal-slot-protection.spec.js
test/membrane/life-red-proxies.spec.js
test/membrane/trap-mutations.spec.js

feat: make arrays, plain objects, and those marked live
Tests are being worked on but getting the initial implementation out for review/discussion.

feat: make arrays, plain objects, and those marked live

---

package.json

chore: tidy release commands a bit

---

packages/near-membrane-base/src/membrane.ts

Inline method calls in callableApply and callableConstruct since these are super hot paths.

feat: inline method calls in callableApply and callableConstruct

---

examples/package.json
lerna.json
package.json
packages/near-membrane-base/package.json
packages/near-membrane-base/src/__tests__/environment.spec.ts
packages/near-membrane-base/src/connector.ts
packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/package.json
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-node/package.json
packages/near-membrane-node/src/__tests__/freezing.spec.js
scripts/package.json
scripts/rollup/plugins/babel-output.cjs
test/environment/createvirtualenvironment-implementation.spec.js
test/membrane/array.spec.js
test/membrane/expandos.spec.js
test/membrane/freezing.spec.js
test/membrane/internal-slot-protection.spec.js
test/membrane/life-red-proxies.spec.js
test/membrane/trap-mutations.spec.js
yarn.lock

[core-236-patch] v0.8.10 backport

[core-236-patch] v0.8.10 backport

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts

feat: batch foreign callables

---

package.json
yarn.lock

chore: update karma to 6.3.17

---

packages/near-membrane-base/src/__tests__/intrinsics.spec.ts
packages/near-membrane-base/src/connector.ts
packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/window.ts
test/membrane/globals.spec.js

feat: add support for lazyRemap (meant as a follow-up to #277)

feat: add support for lazyRemap

---

packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts

chore: comment cleanup

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/window.ts
packages/near-membrane-node/src/node-realm.ts

feat: optimize env.link

---

examples/errors/index.js
packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/window.ts
packages/near-membrane-node/src/node-realm.ts

feat: more optimizing of env.link()

feat: more optimizing of env.link()

---

packages/near-membrane-dom/src/browser-realm.ts

fix: env.link document typo

---

packages/near-membrane-base/src/__tests__/intrinsics.spec.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-node/src/node-realm.ts

feat: use env.lazyRemap() in node-realm

feat: use env.lazyRemap() in node-realm

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts
test/membrane/globals.spec.js

feat: remove unneeded enumerability checks

feat: remove unneeded enumerability checks

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/window.ts
test/membrane/globals.spec.js

fix: round out the chrome bug fix and lazy descriptor wrappers

fix: round out the chrome bug fix and lazy descriptor wrappers

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/window.ts
test/membrane/globals.spec.js

feat: ua sniff the chromium bug fix

feat: ua sniff the chromium bug fix

---

karma.config.js
package.json
yarn.lock

chore: align karma run with locker

chore: align karma run with locker

---

packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-node/src/node-realm.ts

feat: only remap endowments when provided

feat: only remap endowments when provided

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts
test/membrane/instrumentation.spec.js

feat: inline more methods for better performance

feat: inline more methods for better performance

---

packages/near-membrane-base/src/membrane.ts

feat: make `installErrorPrepareStackTrace()` and `debugInfo()` removable as dead code in prod builds.

feat: make installErrorPrepareStackTrace() and debugInfo() removable as dead code in prod builds

---

packages/near-membrane-base/src/membrane.ts

feat: specialize apply/construct trap based on function arity

feat: specialize apply/construct trap based on function arity

---

packages/near-membrane-base/src/membrane.ts

feat: prep instrumentation to be removed during prod builds

feat: prep instrumentation to be removed during prod builds

---

packages/near-membrane-base/src/membrane.ts
packages/near-membrane-node/src/node-realm.ts

fix: adjust types to avoid ts-ignore comments

fix: adjust types to avoid ts-ignore comments

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/index.ts
packages/near-membrane-base/src/instrumentation.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-base/src/types.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/window.ts

feat:  add `PropertyKey` and `PropertyKeys` types

feat:  add PropertyKey and PropertyKeys types

---

packages/near-membrane-base/src/connector.ts
packages/near-membrane-base/src/membrane.ts

fix: remove shared state until it can be shared properly

fix: remove shared state until it can be shared properly

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts

feat: batch and inline more calls

feat: batch and inline more calls

---

packages/near-membrane-base/src/membrane.ts

feat: simplify apply and construct trap optimization

feat: simplify apply and construct trap optimization

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts

feat: inline more and reduce ArrayProtoPush use

feat: inline more and reduce ArrayProtoPush use

---

.nucleus.yaml

chore: update nucleus.yaml

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-node/src/node-realm.ts

feat: less ReflectApply and getDescriptorMeta use

feat: less ReflectApply and getDescriptorMeta use

---

packages/near-membrane-base/src/membrane.ts

feat: continue inlining helpers and reducing the call stack

feat: continue inlining helpers and reducing the call stack

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts

feat: track shadowTarget, inline, and mark properties as readonly

feat: track shadowTarget, inline, and mark properties as readonly

---

packages/near-membrane-base/src/membrane.ts

feat: inline getTransferableValue and add identity function

feat: inline getTransferableValue and add identity function

---

.nucleus.yaml

`enforce-work-item-for-pr` setting was put at the wrong location.

chore: correct settings in .nucleus.yaml

---

packages/near-membrane-base/src/membrane.ts

fix: scrub more call sites

---

packages/near-membrane-base/src/membrane.ts

perf: add back arity specialization.
The benchmarks liked it better when I specialized for arity so bringing the optimization back but in a possibly better way.

perf: add back arity specialization

---

yarn.lock

chore: update caniuse db

---

packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/window.ts

feat: inline getDescriptorMeta() and avoid ArrayProtoPush

feat: inline getDescriptorMeta() and avoid ArrayProtoPush

---

packages/near-membrane-base/src/membrane.ts

fix: pluck lazy descriptor state get/set and inline realm specific callbacks

fix: pluck lazy descriptor state get/set and inline realm specific callbacks

---

packages/near-membrane-base/src/membrane.ts

perf: create a specialized apply trap variant for 3 or more args.
Last stage of the perf revert is to have a variant for 3 or more args too. 
Our expensive path is now rightly the path for any number of args so we want to avoid it if possible.

perf: create a specialized apply trap variant for 3 or more args

---

packages/near-membrane-base/src/membrane.ts

fix: inline lazy state helper calls to avoid var renaming in swc minifier
No functional change.

fix: inline lazy state helper calls to avoid var renaming in swc minifier

---

packages/near-membrane-base/src/membrane.ts

feat: store local copy of cache to avoid foreign calls.
This takes the cache which is generally local per the realm and stores it locally. Only setting it to the shared cache once so others can pick it up. This reduces the foreign callables when interacting with it. Because it's an internal cache and only mutated by setting properties to `false` this is safe to store locally.

feat: store local copy of cache to avoid foreign calls

---

packages/near-membrane-base/src/membrane.ts

chore: conditionally define more methods

chore: conditionally define more methods

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts

feat: more membrane specific conditions to reduce checks when not needed

feat: more membrane specific conditions to reduce checks when not needed

---

packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
test/membrane/document-all.spec.js

perf: add four-arg applyOrConstruct special case
I don't really want this to be a thing. Will see what the perf runs say.

perf: add four-arg applyOrConstruct special case

---

packages/near-membrane-base/src/membrane.ts

fix: add and remove type guards where needed

fix: add and remove type guards where needed

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts

feat: optimize apply/construct trap bail out calls

feat: optimize apply/construct trap bail out calls

---

packages/near-membrane-base/src/membrane.ts

feat: allow registry keys to be minified

feat: allow registry keys to be minified

---

packages/near-membrane-base/src/membrane.ts

chore: update instrumentation activity names

chore: update instrumentation activity names

---

packages/near-membrane-base/src/membrane.ts

feat: more conditional definitions

feat: more conditional definitions

---

packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
scripts/rollup/plugins/babel-output.cjs

feat: more nullish coalescing

---

packages/near-membrane-base/src/membrane.ts

feat: even more conditional defining
It just keeps going 🙃

feat: even more conditional defining

---

packages/near-membrane-base/src/membrane.ts

feat: conditional defining continued
This is becoming a chore 🙃

feat: conditional defining continued

---

packages/near-membrane-base/src/__tests__/connector.spec.ts
packages/near-membrane-base/src/__tests__/environment.spec.ts
packages/near-membrane-base/src/__tests__/intrinsics.spec.ts
packages/near-membrane-base/src/connector.ts
packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/index.ts
packages/near-membrane-node/src/__tests__/error.spec.js
packages/near-membrane-node/src/index.ts
packages/near-membrane-node/src/node-realm.ts
test/environment/createvirtualenvironment-implementation.spec.js
test/environment/membrane.spec.js
test/membrane/membrane-symbols.spec.js

fix: expose serialization to nested blue  proxies

fix: support serialization to blue proxies of other realms

---

packages/near-membrane-base/src/membrane.ts

feat: forward dev mode debug to pointer wrapper

feat: forward dev mode debug to pointer wrapper

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts

feat: cleanup unknown types

---

packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/window.ts

feat: add more error guards and inline a bit more

feat: add more error guards and inline a bit more

---

packages/near-membrane-base/src/membrane.ts
test/membrane/document-all.spec.js

feat: add apply/construct fast path for 5 arguments

feat: add apply/construct fast path for 5 arguments

---

packages/near-membrane-base/src/membrane.ts

chore: cleanup and simplify pass

chore: cleanup and simplify pass

---

examples/custom-elements/index.js
examples/custom-events/index.js
examples/errors/index.js
examples/expandos/index.js
examples/getter-distortion/index.js
examples/invalid-fetch/index.js
examples/object-graph-mutations/index.js
examples/web-components/index.js
test/distortions/getter.spec.js
test/distortions/methods.spec.js
test/dom/custom-elements-extensions.spec.js
test/errors/boundary.spec.js
test/membrane/internal-slot-protection.spec.js

chore: cleanup examples and unit tests

chore: cleanup examples and unit tests

---

packages/near-membrane-base/src/membrane.ts

feat: use `Object.hasOwn` if it's supported

feat: use Object.hasOwn if it's supported

---

packages/near-membrane-base/src/membrane.ts
packages/near-membrane-base/src/types.ts

feat: add accessor types

---

packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts

feat: avoid abstraction for foreign getter/setters

feat: avoid abstraction for foreign getter/setters

---

packages/near-membrane-base/src/connector.ts
packages/near-membrane-base/src/index.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-base/src/utils.ts
packages/near-membrane-dom/src/window.ts

feat: flag a descriptor as foreign in more cases
Redo of #367.

feat: flag a descriptor as foreign in more cases

---

packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts

chore: more types cleanup

---

packages/near-membrane-base/src/membrane.ts

feat: @W-11273923 optimize is-xyz methods

feat: @W-11273923 optimize is-xyz methods

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts

feat: add type checks and remove type checks

feat: add type checks and remove type checks

---

packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/window.ts

minor reduction in document and window getter calls

feat: @W-11465479 minor reduction in document and window getter calls

---

packages/near-membrane-base/src/membrane.ts

Revise minification safe names so that `@locker` packages can minify better.
This PR adds `serializedValue`.

feat: @W-11478158 revise minification safe names

---

scripts/rollup/configs/base.cjs
scripts/rollup/plugins/babel-output.cjs

chore: code style parity with locker

chore: code style parity with locker

---

packages/near-membrane-base/src/membrane.ts
packages/near-membrane-base/src/utils.ts

Missed the de-opt in near-membrane.

fix: @W-11612697 avoid v8 perf de-opt for Array#splice

---

package.json
yarn.lock

Ref: https://github.com/salesforce/near-membrane/commit/b8e5fa524467d3086edc791cef4895a09a0627b8

fix: restore downgrade to karma-rollup-preprocessor to 7.0.7

---

packages/near-membrane-base/src/__tests__/virtualenvironment.spec.ts
packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-base/src/types.ts
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-dom/src/index.ts
packages/near-membrane-dom/src/types.ts
packages/near-membrane-node/src/__tests__/freezing.spec.js
packages/near-membrane-node/src/index.ts
packages/near-membrane-node/src/node-realm.ts
packages/near-membrane-node/src/types.ts
test/dom/liveobject.spec.js
test/environment/virtualenvironment.spec.js
test/membrane/expandos.spec.js
test/membrane/freezing.spec.js
test/membrane/life-red-proxies.spec.js

This allows Locker to tap into and control the liveness of a target.

feat: @W-11665503 add support for liveTargetCallback

---

karma.config.js
packages/near-membrane-base/.eslintrc.cjs
packages/near-membrane-dom/.eslintrc.cjs
packages/near-membrane-node/.eslintrc.cjs
scripts/.eslintrc.cjs
scripts/nyc/report.mjs
scripts/rollup/plugins/babel-output.cjs

chore: @W-11765740 cleanup scripts

chore: @W-11765740 cleanup scripts

---

packages/near-membrane-base/src/environment.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-base/src/types.ts
packages/near-membrane-dom/src/window.ts
packages/near-membrane-shared-dom/src/Document.ts
packages/near-membrane-shared-dom/src/Window.ts
packages/near-membrane-shared-dom/src/__tests__/Window.spec.js
packages/near-membrane-shared-dom/src/index.ts

feat: @W-11801357 `add trackTargetAsFast`

feat: @W-11801357 add trackTargetAsFast

---

packages/near-membrane-base/package.json
packages/near-membrane-dom/.rolluprc.cjs
packages/near-membrane-dom/package.json
packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-node/package.json
packages/near-membrane-shared-dom/package.json
packages/near-membrane-shared/package.json
scripts/rollup/configs/base.cjs
tsconfig.types.json

feat: use exports field in package.json of near-membrane-dom

feat: use exports field in package.json of near-membrane-dom

---

packages/near-membrane-dom/src/window.ts
packages/near-membrane-shared-dom/src/constants.ts
packages/near-membrane-shared-dom/src/index.ts
packages/near-membrane-shared/src/Array.ts
packages/near-membrane-shared/src/RegExp.ts
packages/near-membrane-shared/src/__tests__/Array.spec.js
packages/near-membrane-shared/src/__tests__/RegExp.spec.js
packages/near-membrane-shared/src/index.ts

feat: move chromium sniff to near-membrane-shared-dom

feat: move chromium sniff to near-membrane-shared-dom

---

packages/near-membrane-shared-dom/src/DOMException.ts
packages/near-membrane-shared-dom/src/__tests__/DOMException.spec.js
packages/near-membrane-shared-dom/src/index.ts

feat: expose `DOMException` in shared-dom package

feat: expose DOMException in shared-dom package

---

packages/near-membrane-dom/src/browser-realm.ts
packages/near-membrane-shared-dom/src/constants.ts

fix: @W-12152747 add back old Chromium < v86 eval fix

fix: @W-12152747 add back old Chromium < v86 eval fix

---

packages/near-membrane-base/src/membrane.ts

feat: @W-12147195 don't `Object.freeze` from proxy handlers

feat: @W-12147195 don't Object.freeze from proxy handlers

---

packages/near-membrane-base/src/membrane.ts
test/membrane/binarydata.spec.js

fix: ensure typed array methods don't throw illegal invocation errors

fix: @W-12253063 ensure typed array methods don't throw illegal invocation errors

---

.eslintrc
packages/near-membrane-base/src/__tests__/virtualenvironment.spec.ts
packages/near-membrane-base/src/intrinsics.ts
packages/near-membrane-base/src/membrane.ts
packages/near-membrane-dom/src/browser-realm.ts
test/environment/virtualenvironment.spec.js
test/membrane/async-await.spec.js

chore: cleanup lint warnings

---

packages/near-membrane-base/src/membrane.ts
packages/near-membrane-shared/src/constants.ts

fix: detect minification from function name and not comment removal

fix: @W-12489598 detect minification from function name and not comment removal

---

packages/near-membrane-base/src/membrane.ts
test/membrane/instrumentation.spec.js

chore: @W-13916864 remove unwatched instrumentation

chore: @W-13916864 remove unwatched instrumentation

---

yarn.lock

result of running npx update-browserslist-db@latest
[W-16393397](https://gus.lightning.force.com/a07EE00001y0Rt6YAE)

chore: @W-16393397 Update caniuse-lite in near-membrane

---

.github/actions/setup-workspace/action.yml
package.json

[W-16403700](https://gus.lightning.force.com/a07EE00001y5GNdYAM)

chore: @W-16403700 Update node version in near-membrane

---

packages/near-membrane-base/src/__tests__/intrinsics.spec.ts
packages/near-membrane-base/src/intrinsics.ts

[W-16440795](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001yRVqLYAW/view): Never remap Set and Map regardless of MaxPerfMode or MaxCompatMode

@W-16440795: Never remap Set and Map regardless of MaxPerfMode or MaxCompatMode
