package.json
This PR fixes the `yarn build` command by using the npm package of `realms-shim` (avoids needing to `npm link` etc)
=> use npm package of realms-shim

src/environment.ts, src/reverse-proxy-handler.ts, src/secure-proxy-handler.ts, src/shared.ts
This PR adds some utils to avoid prototype lookups of `.call()` and `.apply()`.
This also uses some of the `Reflect` flavors of methods because they are more forgiving in terms of errors being thrown in many cases (just a preference).
=> Avoid prototype lookups to .call()

src/environment.ts, src/reverse-proxy-handler.ts, src/secure-proxy-handler.ts
Add some missing hasOwnProperty checks to descriptors. Feel free to nit the styling wasn't sure about line length (linting with `--fix` will eventually fix these).
=> add missing hasOwnProperty() checks

src/browser-realm.ts
This just adds a basic sandbox attribute to treat it as same origin and allow script execution. This has a bonus of preventing `window.top.location = ...` changes and a few other things that are all off-by-default. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) for the rest of the off-by-default things. A follow-up would be to use the [allow](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-allow) attribute as well to [disable things like setting `document.domain`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy#Directives) when support lands more broadly (many of them are behind flags or not yet supported by Chrome and others).
=> baby step into sandbox attribute use for browser-realm

src/reverse-proxy-handler.ts, src/secure-proxy-handler.ts
Proxies will walk the prototype of their handlers looking for traps. This prevents them from prototype pollution.
=> null the prototype of proxy handlers

package.json
Fixes #40 
race condition with `ttsc` and `rollup` due to not waiting for completion
=> scripts - build - complete typescript compile before bundle

src/environment.ts, src/shared.ts
To avoid confusion whether our use of `==` is intentional.
Also disable eslint rule just in case and for clarity.
=> Added isNullish shared utility

src/__tests__/error.spec.ts, src/__tests__/reflection.spec.ts, src/browser-realm.ts, src/environment.ts, src/membrane.ts, src/node-realm.ts, src/reverse-proxy-handler.ts, src/secure-proxy-handler.ts, src/shared.ts
This PR identifies areas where:
* a sandbox calls into the outer realm which might throw.
* a membrane procedure throws an error.
* proxy and array for the sandbox should be from the sandbox intrinsics.
* remapping all intrinsic error constructors between the two realms.
* abstraction membrane operations and types into its own file.
* revoked or broken targets should be represented via a revoked proxy.
* extracting target meta during proxy construction to avoid leaking mutations before the initialization of the secure proxy.
=> fixes #8: basic implementation of the error boundaries

examples/custom-elements.js, examples/custom-events.js, examples/errors.html, examples/errors.js, examples/expandos.js, examples/getter-distortion.js, examples/invalid-fetch.js, examples/object-graph-mutations.js, examples/web-components/platform.js, src/__tests__/error.spec.ts, src/__tests__/freezing.spec.ts, src/__tests__/index.spec.ts, src/__tests__/reflection.spec.ts, src/browser-realm.ts, src/environment.ts, src/membrane.ts, src/node-realm.ts, src/reverse-proxy-handler.ts, src/secure-proxy-handler.ts, src/shared.ts
Changes:
* changed the public api of `environment.ts` to return a evaluator function per environment rather than the chaining of the secure global passed as argument.
* move evaluation of the proxy factory for secure objects into the sandbox via indirect eval.
* simplification of the environment.ts to be the record holder and be resilience to stack overflows.
* adjust all tests to rely on `expect` inside and outside the sandbox.
* protect against poisoning of the global eval
Related to https://github.com/caridy/secure-javascript-environment/issues/48
=> Error Boundary: avoid leaking globals from sandbox

src/environment.ts, src/secure-value.ts, test/distortions/getter.spec.js
The bug identified by @dejang and Ted is the result of having a different behavior for global descriptors, where the getter of any global descriptor (of globalThis) will not get distorted. This PR fixes that, but I will argue that eventually we should look for a solution that doesn't require a different code-path for global descriptors vs other descriptors.
=> fixes #64: preserving distortion capability for global property accessors

src/raw-value.ts, src/secure-value.ts
This makes the shadow target's not have a `'prototype'` if the raw value does not have a `prototype`. It also has a bonus of making them non-constructable too which is generally the case (maybe always the case).
=> make target functions that more closely mimic their raw functions

src/browser-realm.ts, src/shared.ts
In the case of the browser sandbox, crypto to be the first one in the list.
this is a partial solution, assuming that:
1. crypto is not dangerous (or give you any authority)
2. crypto to function even on detached iframes (confirmed)
=> issue #67: adding a list of dom APIs that can be reflective

src/browser-realm.ts
Since some policy feature flags are supported I went ahead and added the directives to disable them just in case someone was able to break out.
=> add policy restriction to iframe

src/__tests__/freezing.spec.ts, src/browser-realm.ts, src/node-realm.ts, src/raw-value.ts, src/secure-value.ts, src/shared.ts, test/dom/custom-element.spec.js, test/membrane/internal-slot-protection.spec.js
This PR introduces a new way to control reverse proxies (proxies accessible on the outer realm for objects that were declared inside a sandbox), and here are the details:
* LWC freezes (in dev-mode) the custom elements declared inside a sandbox.
* any metaprogramming (e.g.: decorators) will attempt to decorate a class/prototype from a sandbox.
* any DOM api that observes changes in objects (e.g.: console.log) was not updating the values due to the snapshotting of the values in the membrane.
This PR relaxes that by supporting live objects via reverse proxies.
* LWC components can work with new locker.
* it is easier to debug code using `console.log` statements.
* it is faster to create proxy objects since we don't take the initial snapshot anymore.
* poisoning is now easier to achieve, the …
=> [refactor] relaxing the semantics of the reverse proxies to allow live objects

src/environment.ts, src/raw-value.ts, src/secure-value.ts, src/types.ts
When storing the double entry in the maps, we use a now unnecessary record that holds ref to sec and raw, as the value on both maps. It turns out that the record is not needed, and it can be just a simple map with the crossed references.
This change reduces the memory allocation, and should improve perf as well.
=> [simplification] removing extra record used to store map between sec and raw refs

src/environment.ts, src/raw-value.ts, src/secure-value.ts, src/shared.ts, test/membrane/document-all.spec.js
This PR fixes https://github.com/caridy/secure-javascript-environment/issues/76
=> fixes #76: document.all == null breaks the membrane for valid targets

src/environment.ts, src/raw-value.ts, src/secure-value.ts
Based on some feedback from @ljharb on https://github.com/caridy/secure-javascript-environment/pull/77#discussion_r394397511, we can now validate that in seems that the parser can understand better the intent and optimize the comparison (to avoid string comparison) when the typeof is inline.
=> letting engine to optimize typeof comparisons

src/secure-value.ts, test/membrane/document-all.spec.js
As a follow up from PR https://github.com/caridy/secure-javascript-environment/pull/77, and after reviewing the current usage of this feature:
https://www.chromestatus.com/metrics/feature/timeline/popularity/83
I have reviewed some of the websites that are using this feature, all of them are just simply relying on the undefined nature of the value to detect something. It seems that the detection of the value being undefined is more important that the feature itself, and for that reason, we should favor the detection. In this PR, we are making the value `undefined` inside the sandbox, which means that you will never be able to access the collection itself, you have others means for that.
=> disabling document.all inside a sandbox

src/blue.ts, src/red.ts, test/membrane/cross-ns-extensions.spec.js, test/membrane/object-semantics.spec.js
This PR fixes the issue with namespace to namespace class extensions that were reporting the incorrect prototype value on constructors.
The issue was that when a shadowTarget is a function, it comes by default with two non-configurable, writable properties defined, `name` and `prototype`. In the code, we were always attempting to read the descriptor from the shadowTarget first, and then from the target if it didn't exist in the shadowTarget, and this, of course, was returning the wrong prototype value.
With this PR, we adjust the logic to never ever return the value from a shadowTarget on a blue proxy, instead, we always read the value from the real target, and we use the shadowTarget only to preserve the semantics of the language (the object invariants).
=> fix: namespace to namespace class extensions

src/browser-realm.ts, test/dom/unforgeables.spec.js
This PR adjust our model to the following:
1. `EventTarget.prototype` continues to be unforgeable (it is accessible from `window.__proto__.__proto__.__proto__`
2. `EventTarget.prototype` gets map to  `EventTarget.prototype`  from the other side.
3. all descriptors in `EventTarget.prototype`  are replaced with proxies to their corresponding blue side.
4. `EventTarget` is replaced with the blue `EventTarget`.
Btw, this issue was affecting chrome only because for some reason, they are deleting the global `EventTarget` when the iframe is detached. Replacing it with a proxy of the blue one fixes that.
=> fix #85: global EventTarget is configurable and can be replaced after remapping its prototype to the sandbox prototype, which is unforgeable

src/browser-realm.ts
Porting fix from `next` branch to master. 
This fix addresses the scenario when SJS is loaded in the `<head>` of the page as a `script` tag. At the time of load `body` will not be available and code will crash with `document.body is null` error. This fix addresses this case such that the iframe is appended right after the `<script>` tag that loads SJS. 
The iframe will be removed later on so no need to worry about polluting the DOM with iframe tags.
=> Append iframe to last known parent instead of body

src/__tests__/freezing.spec.ts, src/blue.ts, src/red.ts, src/shared.ts, test/membrane/life-red-proxies.spec.js, test/membrane/object-graph-mutations.spec.js
Most red proxies will use the snapshotting technique to prevent sandboxed code to affect the integrity of the blue realm by mutating those object, but there are certain exceptions to this rule.
This PR introduces a new controlled mechanism that allows developers to mark certain objects as live objects, and in that case, the sandboxed code will have the ability to mutate the descriptors installed on that object. E.g.:
```js
const magicSymbol = Symbol.for('@@lockerLiveValue');
const blueObj = { x: 1 };
Reflect.defineProperty(blueObj, magicSymbol, {});
```
In the example above, if a red realm get access to `blueObj` via a red proxy, that proxy will not do snapshotting, but will support live values, and potential mutations on that object.
This also fixes …
=> fixes #63: adding new capability to support live red proxies

src/blue.ts, src/shared.ts, test/membrane/blue-expandos.spec.js
This PR implement a new invariant that membrane should never switch sides when get/set/has traps are called because it looses track of the initiator of the interaction, which determines whether or not you can see distortions or mutations from red.
This code is mostly copied from red.ts, where we have already implemented those semantics, it turns out that this was also needed in blue.ts otherwise you might ended up effected by mutations or distortions only visible in the red side because these 3 traps were switching sides by calling Reflect.set/get/has on the red side.
This issue was identified by @dejang, and is reproducible by the following code:
```js
import createSecureEnvironment from '../../lib/browser-realm.js';
class Base {
constructor() {
this.statusVariable = 'initial';
}
}
let …
```
=> Implement Crossing Membrane Invariant in Blue Handler

package.json, src/blue.ts, src/red.ts, test/membrane/blue-expandos.spec.js, test/membrane/null-protos.spec.js
there were 6 places were we retrieve the `__proto__`, and we were not protecting against that being `null` in the following lines. This PR takes care of that, plus add some more types protections.
=> fix: guarding against null prototypes

src/blue.ts, src/red.ts, test/membrane/invariant.spec.js
When locking down the shadowTarget of a dynamic proxy (both blue and red), we were not adjusting the `__proto__`, causing that any proto chain lookup after setting the object to not extensible to report an invariant violation.
=> fix issue with dynamic red and blue proxies that can be now freeze without invariant violations

src/blue.ts, src/red.ts, test/membrane/ownKeys.spec.js
This PR addresses #96 and avoids ownKeys trap invariant errors for classes and strict mode functions.
=> fix: ownKeys trap for classes and strict mode functions

test/membrane/promises.spec.js
Adding tests for promises to be settled.
Note: the test fails in Firefox but passes in Chrome, not sure why.
Related to W-7706722.
=> test: Added test for promises to be settled

src/shared.ts
This PR fixes promise resolving in Firefox/Safari for promises created with `Promise`. It does not address those created with `async await`.
=> fix(x-realm) ensure promises created with Promise resolve

src/red.ts
When sent to the client in a minified script (terser), `serializedRedEnvSourceText` value starts with `function(t,e){'use strict'const n=Symbol.for(\"@@lockerLiveValue\"), [...]}` which fails to evaluate with `SyntaxError: unexpected token: keyword 'const'`.
=> fix: add semicolon to 'use strict' directive in serializedRedEnvSourceText

src/blue.ts, src/browser-realm.ts, src/node-realm.ts, src/red.ts, src/shared.ts, test/membrane/error.spec.js
A discrepancy in the behavior of errors in Promises lead to the following refactor. See below
```
// in red:
promise1 = new Promise(() => { throw {foo: 'bar' })
promise2 = new Promise((resolve, reject) => reject({foo: 'bar'}))
// in blue
promise1.catch(e => console.log(e.foo)) // undefined
promise2.catch(e => console.log(e.foo)) // bar
```
This inconsistency led to a deeper analysis of how errors were handled previously and the need to align the behavior in both promises but also functions and constructors.
=> refactor(membrane): red to blue and vice-versa errors

test/membrane/promises.spec.js
This PR adds 2 tests, `throw should be supported with errors` pass but `throw should be supported with non-errors` fails. 
It seems like we are assuming that exceptions thrown are `Error` instances or at least will have a `message` field and a constructor? https://github.com/caridy/secure-javascript-environment/blob/481234e1f99ca5c510ad106489ce5c7918b3d0e5/src/blue.ts#L173
Is it a bug or am I doing something wrong?
=> test: throw should be supported in promises

src/browser-realm.ts, src/node-realm.ts, test/membrane/async-await.spec.js
Starting with a basic test for wrapping promises, we may want to add more tests.
At this point: Chrome:pass, Firefox:fail, Safari:fail
(also added missing imports prob should be in separate PR)
=> Adding async/await tests

test/membrane/async-await.spec.js
=> For now: skip async/await tests for Firefox and Safari

src/browser-realm.ts
It see that `allow` has no effects on the DOM API identity defined in the iframe, and since all DOM APIs are remapped to the blue realm, providing the `allow` attribute has no effects whatsoever in the sandbox. It doesn't cause any harm either, but increases the size of the bundle. For those reasons, I believe it is safe to remove it.
=> removing unnecessary attribute in iframe

.github/workflows/main.yml, package.json, rollup.config.js, tsconfig.json, yarn.lock
In order to test for the size of the bundle, we have to actually bundle the library. Because there are two entry points, I am creating two bundles, _index_ which exports `SecureEnvironment` and _browser-realm_ which exports `createSecureEnvironment`. Result in the lib folder is:
```
- /lib
browser-realm.js
browser-realm.min.js
browser-realm.map.js
node-realm.js
node-realm.min.js
node-realm.map.js
index.js
index.min.js
index.map.js
```
Current minified bundle size for each is index: 8.9KB and browser-realm: 12.5KB
I was also able to clean things up a bit by upgrading rollup. (fixes #123)
=> feat: testing for bundle size increases

src/intrinsics.ts, src/shared.ts, test/membrane/reversed-proxy-constructor.spec.js
I believe this is all that's needed to avoid wrapping `Proxy`.
=> fix(environment) add Proxy to ReflectiveIntrinsicObjectNames

src/browser-realm.ts, src/window.ts
Based on your investigation this PR avoids unneeded calls to `Object.getOwnPropertyDescriptors()` for red global objects.
=> feat(core) Improve sandbox creation perf by avoiding getOwnPropertyDescriptors on red globals

src/blue.ts, src/environment.ts, src/red.ts, src/shared.ts
As uncovered by @dejang, using `Object.defineProperties` instead of individual `Reflect.defineProperty` or `Object.defineProperty` calls yields better performance ~150ms better in his benchmark runs.
=> feat(core) Improve performance by using Object.defineProperties

.circleci/config.yml
@caridy [Chrome tests work on CircleCI](https://app.circleci.com/pipelines/github/salesforce/near-membrane/4/workflows/955894c3-ca9e-4bf4-8189-ec201aae0161/jobs/5/parallel-runs/0/steps/0-107)
=> Enable Chrome for Karma tests

src/red.ts
Add comment to disable istanbul for serialized code
@caridy this is a non-functional change to help @arcadeteddy with Karma test coverage. He tried to add this comment dynamically using a script in locker repo, but the script is failing (see [here](https://app.circleci.com/pipelines/github/salesforce/locker/1740/workflows/4dc02c2f-daff-4582-8c35-71960922cea8/jobs/2669/parallel-runs/0/steps/0-104)) and would be hacky to try to make it work, I think adding this comment here is the right long term solution. The comments are preserved in the npm package.
=> Istanbul integration

packages/near-membrane-base/src/blue.ts, packages/near-membrane-base/src/red.ts, packages/near-membrane-base/src/shared.ts
I noticed we didn't store references to the `TypeError` constructors, so fixed that.
=> fix(core) Store reference to TypeError constructors

packages/near-membrane-base/src/blue.ts, packages/near-membrane-base/src/red.ts
While QAing the package split it was discovered that our karma tests were failing in Locker. This is due to a regression I caused with the performance work to near-membrane.
=> fix(core) Address regression in descriptor helpers

test/membrane/internal-slot-protection.spec.js
- fixed: was creating distortion map from undefined setter
- fixed: was creating Map with incorrect args.
=> fix: use descriptor.value for setAttribute function in internal slot protection test

packages/near-membrane-base/src/__tests__/shared.spec.ts
Before: 
After: 
The tests here reach the parts that aren't being indirectly reached by other tests. 
Eventually, I'd like to have full "standalone" coverage for all of these modules.
=> test: @W-9323615@ near-membrane-base/src/shared.ts to 100% coverage

package.json, packages/near-membrane-base/src/__tests__/shared.spec.ts, packages/near-membrane-base/src/shared.ts
As part of the QA for code coverage of near-membrane-base I ran into a rough spot making sure I was seeing the right numbers, so made the script easier and then found some dead code (as my numbers reported are ~96%).
=> feat: make coverage script more user friendly and remove dead code

packages/near-membrane-base/src/intrinsics.ts, packages/near-membrane-dom/src/browser-realm.ts, packages/near-membrane-node/src/node-realm.ts
This is the beginning of work to eventually clean up stack traces. We'll need to transform method names in order to detect and filter them. But that's next release.
=> feat: expand call stack limit for red realm

.eslintrc, packages/near-membrane-base/src/blue.ts, packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/red.ts, packages/near-membrane-base/src/types.ts
The main objective here is to introduce the concept of the shape of the remote proxy when creating those proxies rather than doing direct inspection of the target when creating the proxy because in a callable boundary scenario, you will never have access to the actual target.
=> refactor: moving closer to add callable boundary support (step 1)

packages/near-membrane-base/src/red.ts
This is coming in for a patch release:
Avoid object spread inside the serialized `redEnvFactory`.
This will be taken care of in the future with the callable boundary PR (#178)
=> fix: avoid object spread inside the serialized redEnvFactory

packages/near-membrane-base/src/membrane.ts
Previously, when processing the `ReflectIntrinsicObjectNames`, near-membrane-base was guarding against the possibility of one of the names not existing in the runtime, ie. `AggregateError` (https://github.com/salesforce/near-membrane/blob/33938f60a514d5e72d84d309a5cb42c5fba24ee2/packages/near-membrane-base/src/intrinsics.ts#L151-L171). This restores that protection.
=> fix: guard against globals that may not yet exist in a given runtime

packages/near-membrane-base/package.json, packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/intrinsics.ts, packages/near-membrane-base/src/membrane.ts, packages/near-membrane-dom/package.json, packages/near-membrane-node/package.json
* Avoid object spread (avoid transpiling with Babel helpers for Edge Legacy)
* Use loops instead of `Array#map` in hot path
* Consistent naming
* `"sideEffects": false` (for non-rollup bundlers within Salesforce)
=> feat: avoid object spread, use loops instead of `Array#map` in hot path, etc.

packages/near-membrane-base/src/__tests__/environment.spec.ts, packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/intrinsics.ts, packages/near-membrane-base/src/membrane.ts, packages/near-membrane-dom/src/browser-realm.ts, packages/near-membrane-dom/src/index.ts, packages/near-membrane-dom/src/window.ts, packages/near-membrane-node/src/node-realm.ts
This is the step 1 toward support for multi-window/multi-doc in locker. This PR will allow a distortion to create a virtual environment to connect an iframe with an existing virtual environment.
=> refactor: moving the reflection logic out of VirtualEnvironment

packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/intrinsics.ts, packages/near-membrane-dom/src/window.ts
Based on the following discussion: https://github.com/salesforce/near-membrane/pull/192#issuecomment-926938701
=> refactor: using list instead of string split for path

packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/membrane.ts, packages/near-membrane-dom/src/browser-realm.ts, packages/near-membrane-dom/src/index.ts, packages/near-membrane-node/src/index.ts, packages/near-membrane-node/src/node-realm.ts
* to get access to the `init` method, you must execute the callable marshall creation mechanism first for caching intrinsics
* `createVirtualEnvironment` now returns the instance of the `env`, so we can access certain things out of that environment directly.
* `env.blueConnector` and `env.redConnector` are now available to locker can cache them, and reuse them for multi-window support
* most of the changes are indentation after adding an extra wrapping function
* this PR enables the ability in locker to create arbitrary membranes across existing realms.
Since this API is changing, a lot of other areas will be affected:
=> refactor: introduce marshall creation around init to reuse intrinsics and other shared values

babel.config.js, packages/near-membrane-base/src/membrane.ts
Lack of globalThis is breaking Android emulators running Chrome 69.
=> fix: add globalThis polyfill

packages/near-membrane-base/src/connector.ts, packages/near-membrane-base/src/membrane.ts
Adds the `Error.prepareStackTrace` handler for sandboxes created to cleanup stack traces in Chrome.
=> feat: add Error.prepareStackTrace handler @W-10270228

test/membrane/trap-mutations.spec.js
This PR is related to https://github.com/salesforce/near-membrane/pull/237, it adds a couple of tests that might highlight observable differences with respect to that PR that we need to either fix or document.
=> test: validating assumptions about trap mutations

packages/near-membrane-dom/src/browser-realm.ts
This was a debatable add and now it's inconsistent so simply using `[]` instead of `emptyArray` references.
Related to https://github.com/salesforce/locker/pull/620.
=> chore: remove emptyArray use

packages/near-membrane-base/src/intrinsics.ts
fix: correct typo in ESGlobalsAndReflectiveIntrinsicObjectNames
=> fix: correct typo in ESGlobalsAndReflectiveIntrinsicObjectNames

.eslintrc, packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/membrane.ts, test/dom/membrane-symbols.spec.js, test/membrane/object-branding.spec.js, test/membrane/symbols.spec.js
feat: support membrane symbols
This is the ground-work for structured clone support https://github.com/salesforce/locker/pull/617
by adding support for 2 new membrane symbols:
- `Symbol.for('@@lockerNearMembrane')`
- `Symbol.for('@@lockerNearMembraneSerializedValue')`
These symbols act as if they don't exist but when access will return a value
```js
const LOCKER_NEAR_MEMBRANE_SERIALIZED_VALUE_SYMBOL = Symbol.for('@@lockerNearMembraneSerializedValue');
const LOCKER_NEAR_MEMBRANE_SYMBOL = Symbol.for('@@lockerNearMembrane');
LOCKER_NEAR_MEMBRANE_SYMBOL in myMembraneProxiedObject // => false
LOCKER_NEAR_MEMBRANE_SERIALIZED_VALUE_SYMBOL in myMembraneProxiedObject // => false
```
However on an unshadowed accessed:
```js
myMembraneProxiedObject[LOCKER_NEAR_MEMBRANE_SYMBOL] // => true …
```
=> feat: support membrane symbols

packages/near-membrane-base/src/membrane.ts, test/membrane/membrane-symbols.spec.js, test/membrane/symbols.spec.js
This PR codifies the gate procedure of checking if a near-membrane symbol exists via the `has()` trap BEFORE accessing its value via the `get()` trap. By doing this we enforce this check which we where doing double-y before (in near-membrane and in locker) and make it part of the magic incantation of access. So this makes it less likely to be faked and optimizes our checks to boot.
=> feat: optimize near-membrane symbol gate

.eslintrc, packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/membrane.ts, packages/near-membrane-node/src/__tests__/freezing.spec.js, test/membrane/expandos.spec.js, test/membrane/freezing.spec.js, test/membrane/life-red-proxies.spec.js, test/membrane/membrane-symbols.spec.js, test/membrane/object-branding.spec.js, test/membrane/trap-mutations.spec.js
feat: add array buffer and regexp (because of .lastIndex) to live objects, no longer memoize toStringTags, and add lots of tests.
=> feat: add array buffer and regexp to live objects, no longer memoize toStringTags

packages/near-membrane-base/src/membrane.ts
feat: all lint guard for prefer-object-spread in toString-able functions.
While we have guards in place and have explicit opt-outs before use, those are more a signal to us not to change them into an object spread. This helps prevent transforms in case they are used anyways and aligns with what we do in our `@locker/sandbox` package.
=> feat: all lint guard for prefer-object-spread in toString-able functions

package.json, yarn.lock
As found here: https://github.com/jlmakes/karma-rollup-preprocessor/issues/75
Related to https://github.com/salesforce/locker/pull/771
=> fix: downgrade karma-rollup-preprocessor to 7.0.7 to address file overwrite issue

packages/near-membrane-base/src/membrane.ts
feat: use NumberIsInteger instead of a heavy regexp check
=> feat: use NumberIsInteger instead of a heavy regexp check

packages/near-membrane-base/src/connector.ts, test/environment/create-connector-spec.js
fix: create a different connector for the same window object with a different location
=> fix: create a different connector for the same window object with a different location

packages/near-membrane-base/src/__tests__/intrinsics.spec.ts, packages/near-membrane-base/src/intrinsics.ts
If JSON is prevented from remapping, then the distortion for JSON.parse is not applied. Discovered via coverage reports: 
Tested by building this patch and local linking into locker, then running coverage.
=> fix: @W-11903379@ chore: remove JSON from ESGlobalKeys to allow distorting JSON.parse

packages/near-membrane-base/src/membrane.ts
fix: @W-11955893 ensure fastForeignTargetPointers exists before use
=> fix: @W-11955893 ensure fastForeignTargetPointers exists before use

packages/near-membrane-dom/src/browser-realm.ts, packages/near-membrane-dom/src/types.ts, packages/near-membrane-shared/src/Function.ts
Adding an extra config options to the Browser Environment options bag. This allows passing a function which should return a TrustedType object meant to be used when creating the redConnector. This function does not propagate downstream to every `eval` call and should not do that unless there is a really solid reason to automatically sign every string we eval in the iframe.
=> feat: trustedCreateScript browser env option

packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/types.ts
fix: ensure red callable functions have undefined 'this' context
=> fix: ensure red callable functions have undefined 'this' context

packages/near-membrane-base/src/__tests__/intrinsics.spec.ts, packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/membrane.ts, packages/near-membrane-base/src/types.ts, packages/near-membrane-dom/src/browser-realm.ts, packages/near-membrane-node/src/node-realm.ts, packages/near-membrane-shared/src/NearMembrane.ts, packages/near-membrane-shared/src/__tests__/NearMembrane.spec.js, packages/near-membrane-shared/src/constants.ts, packages/near-membrane-shared/src/types.ts, test/dom/custom-element.spec.js, test/membrane/json.spec.js, test/membrane/membrane-symbols.spec.js
feat: add `env.installRemapOverrides()` for better json support
=> feat: @W-12499107 add env.installRemapOverrides() for better json support

packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/membrane.ts, packages/near-membrane-dom/src/custom-devtools-formatter.ts, packages/near-membrane-shared/src/Function.ts, packages/near-membrane-shared/src/NearMembrane.ts, packages/near-membrane-shared/src/Proxy.ts, packages/near-membrane-shared/src/Reflect.ts, packages/near-membrane-shared/src/__tests__/Function.spec.js, packages/near-membrane-shared/src/__tests__/NearMembrane.spec.js, packages/near-membrane-shared/src/__tests__/Proxy.spec.js, packages/near-membrane-shared/src/__tests__/Reflect.spec.js, packages/near-membrane-shared/src/clone.ts, packages/near-membrane-shared/src/constants.ts, packages/near-membrane-shared/src/index.ts, packages/near-membrane-shared/src/types.ts, test/__bootstrap__/3rdparty/expect.assertions.js, test/__bootstrap__/3rdparty/reset-global.js, test/membrane/date.spec.js, test/membrane/json.spec.js, test/membrane/membrane-symbols.spec.js
feat: @W-12539773 add `isNearMembraneProxyMaskedFunction()`
=> feat: @W-12539773 add isNearMembraneProxyMaskedFunction()

packages/near-membrane-base/src/environment.ts, packages/near-membrane-base/src/membrane.ts, packages/near-membrane-base/src/types.ts, packages/near-membrane-dom/src/browser-realm.ts, packages/near-membrane-node/src/node-realm.ts, test/membrane/json.spec.js
fix: revert `env.installRemapOverrides()` to bring back later to fix a performance regression.
=> fix: revert env.installRemapOverrides() to bring back later

packages/near-membrane-dom/src/browser-realm.ts, test/dom/create-virtual-environment.spec.js
fix: @W-12721159 revoke proxy of kept alive iframe contentDocument and contentWindow instead of iframe itself.
=> fix: @W-12721159 revoke proxy of kept alive iframe contentDocument and contentWindow

packages/near-membrane-base/src/intrinsics.ts, test/membrane/json.spec.js
chore: @W-12740677 revert JSON to being non-remapped
=> chore: @W-12740677 revert JSON to being non-remapped

packages/near-membrane-base/src/intrinsics.ts
fix: @W-13107837 add missing 'webkit' property for WKWebView
=> fix: @W-13107837 add missing 'webkit' property for WKWebView

packages/near-membrane-dom/src/window.ts
DOM used by Jest is missing some functionality. This is to guard against a null EventTargetProto
=> chore: Guard for Jest DOM

packages/near-membrane-base/src/membrane.ts
fix: @W-14690711 bypass Chrome JIT bug in `setPrototypeOf` proxy trap
=> fix: @W-14690711 bypass Chrome JIT bug in setPrototypeOf proxy trap

packages/near-membrane-base/src/__tests__/intrinsics.spec.ts, packages/near-membrane-base/src/intrinsics.ts, packages/near-membrane-dom/src/browser-realm.ts, packages/near-membrane-dom/src/types.ts, packages/near-membrane-node/src/node-realm.ts, packages/near-membrane-node/src/types.ts
Introducing a new configuration option when a VirtualEnvironment is being created: `remapTypedArrays`. 
This allows the creator of the sandbox to control whether TypeArrays will use the environment's own prototypes (Red) or the Blue ones. 
In situations where a specific piece of code does TypeArrays manipulation at scale (50k+ entries) this option could be considered in order to drastically improve performance of the code running in the Red realm.
By default remapping is enabled and the option requires passing explicitly `false` in order to be disabled.
=> feat: optional TypeArrays remapping in realm

packages/near-membrane-dom/src/browser-realm.ts, test/membrane/binary-data.spec.js
The globalObjectKeys cache was interfering with the remapTypedArrays optimization. When creating an environment from the same global object, `remapTypedArrays` would not behave as expected because cached global object keys would take priority over the sandbox configuration to exclude certain intrinsics (aka some global object keys).
=> fix: remove global object keys cache

test/membrane/binary-data.spec.js, test/membrane/untrusted/binary-data/FileSaver-blue-blob.js
[W-16404595](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001y5CERYA2/view): Add Identity Discontinuity test cases for MaxPerfMode to near-membrane's binary data tests
=> @W-16404595: Add Identity Discontinuity test cases for MaxPerfMode to near-membrane's binary data tests

packages/near-membrane-base/src/intrinsics.ts, test/membrane/binary-data.spec.js, test/membrane/untrusted/binary-data/create-imagebitmap-blob.js, test/membrane/untrusted/binary-data/create-imagebitmap-imagedata.js, test/membrane/untrusted/binary-data/fetch.js, test/membrane/untrusted/binary-data/request.js, test/membrane/untrusted/binary-data/response.js, test/membrane/untrusted/binary-data/xhr-send.js
[W-16440739](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001yRVhxYAG/view): Implement other MaxPerfMode tests based on W-16299351 inventory
=> Add more maxPerfModeKeys and realated tests

packages/near-membrane-base/src/intrinsics.ts, test/membrane/binary-data.spec.js, test/membrane/untrusted/binary-data/text-decoder.js, test/membrane/untrusted/binary-data/text-encoder.js
[W-17310064](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000025zvbyYAA/view?ws=%2Flightning%2Fr%2FADM_Work__c%2Fa07EE000023VcfqYAC%2Fview): [LWS] Add TextDecoder to near-membrane maxPerfMode keys to fix "TypeError: parameter 1 is not of type 'ArrayBuffer'" | Work
=> fix: @W-17310064 [LWS] Add TextDecoder to near-membrane maxPerfMode keys to fix "TypeError: parameter 1 is not of type 'ArrayBuffer'"
